spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 445854572331-cjtvvmd5bapl6r7usct4vrtr8hrpsv9u.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    # 테이블 생성 후에 data.sql 실행
    defer-datasource-initialization: true

  datasource: # 데이터베이스 정보 추가
    url: jdbc:h2:mem:testdb
    username: sa
  h2: # H2 콘솔 활성화
    console:
      enabled: true
jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot